FROM docker.io/node:gallium-slim

# Install full Chromium
RUN apt-get update && apt-get install chromium -y

# Still needs the Puppeteer Chromium installation
# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

ENV HOST=0.0.0.0
ENV PORT=8000
ENV POST_GPT_URL='https://us-central1-post-gpt.cloudfunctions.net/chatgpt'
ENV LOGIN_URL='https://us-central1-post-gpt.cloudfunctions.net/login'

WORKDIR /app

RUN adduser --system --group zapgateway

COPY . zapgateway
RUN chown -R zapgateway:zapgateway .

RUN npm i --prefix zapgateway --omit=dev --only=production

EXPOSE 8000
CMD [ "node", "zapgateway" ]
