# fly.toml file generated for zapgateway on 2023-04-15T20:55:39-03:00

app = "zapgateway"
primary_region = "gig"

[http_service]
  internal_port = 8000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
